### ISSUE TITLE
[BUG] Pearl Module Preset "stop" action does not work on Recorder/Publisher

### ISSUE THREAD

**Issue by AustinStearns** [bitfocus/companion-module-epiphan-pearl#10]
Describe the bug:
When using the latest Companion build with an Original Pearl the preset companion buttons on recorder or publisher to  trigger the "start" action work fine but fail on the "stop" action.
The companion feedback stays true to the hardware state, but the action does not send the correct information to the hardware to stop recording or streaming. After "unlatching" the button to stop recording/streaming the red stop icon shows in the top right corner of the button and the instance on the connections tap shows an error.  The debug log shows "21.06.01 12:48:45 instance(PEARL REC A): The was called for a unknow action: 0".

To Reproduce:
Add Preset Recorder/Publisher button for a connected Original Pearl Hardware interface to a button
Click on the button to trigger down action (Start) (works fine to start recording)
Click on the button to trigger up action (Stop) (does not work and sends error to instance when trying to stop recording)

Expected behavior:
The unlatch click of a button should correctly stop the recorder or publisher.

Desktop:
OS: Win10 Pro 21H1 19043.985
Browser: Chrome Version 91.0.4472.77 (Official Build) (64-bit)
Companion Version: (Latest 6/1/21) v2.2.0 (24a2d29d-3352)
Pearl Version: ESP1002 – Epiphan Systems Pearl Rackmount Twin (Original, not Pearl 2)
Pearl Firmware Version: 4.12.01 (50513_1830) 
Pearl Hardware Version: CPU Board: D53427RKE (G87790-407) BIOS: 11/05/2014

I can give someone willing to troubleshoot access to our system and pearl if that would help in debugging the issue.  I've reset our APP DATA folder and tried reinstalling and starting from scratch and tried several versions of the beta builds with the same broken "stop" action.  Thank you in advance.

**Comment by MarcHagen** [comment]
Hi there,

Thanks for the detailed description. If i need more info i'l ask here.

**Comment by MarcHagen** [comment]
So quick update, i see what's happening, but in kinda lost why. 
The `unknow action: 0` is wierd because 0 is a valid action. 
I'll have to dig deeper.

**Comment by AustinStearns** [comment]
Thank you @MarcHagen for taking a look.  Let me know if we can help test or provide more information.

**Comment by MarcHagen** [comment]
Okay yeah i found it, simple bug from my side. Will update the module and get it in the latest release.

**Comment by MarcHagen** [comment]
@AustinStearns Fixes have been pushed to companion and should be available in one of the latest dev builds.

**Comment by AustinStearns** [comment]
@MarcHagen Thank you for your quick work on the fix.
