### ISSUE TITLE
Audio Gain and Attenuation

### ISSUE THREAD

**Issue by Jasevi** [bitfocus/companion-module-epiphan-pearl#13]
Hi there,

Would it be possible to control the audio gain and attenuation in this module? Could it be added?

Thank you so much.

**Comment by MarcHagen** [comment]
Hi there!
Took me a bit too see if this is possible, but unfortunately there is no good way to provide a feature like this.
We are restricted to the "new live UI" of the Pearl and there is no option to do so.
_Correct me if im wrong_
