### ISSUE TITLE
new development

### ISSUE THREAD

**Issue by fbosman** [bitfocus/companion-module-epiphan-pearl#18]
I need further development of this module:
More feedbacks,
V3 compatible and
 channel Lay-out switch’s 

Do you mind if I take up these tasks or can you do them yourselves?

**Comment by dnmeid** [comment]
Hi Frans,
a complete rewrite of the module for v3 compatibility is currently in preparation with the support of Epiphan.
I hope to have more information next week and the module should be done within the next 2-3 weeks.

**Comment by fbosman** [comment]
Hi, any updates on this?
