### ISSUE TITLE
API Info from Pearl Device

### ISSUE THREAD

**Issue by gotfox** [bitfocus/companion-module-epiphan-pearl#20]
I'm not certain that this is documented from Epiphan at all or if this info has already been used for the module already, but you can access onboard API functions by going to this URL on the Pearl device:
http://[device_ip_address]/admin/http_api.cgi

This is what my Pearl 2 generates:
`
<div class="container">

<h1>
Pearl-2 HTTP API
</h1>

<p>
Some of the configuration parameters of Pearl-2 can be queried and modified
non-interactively via http(s). The point is to be able to control the device remotely
from a script or from a program.
</p>

<p>The syntax of get/set requests for system-wide parameters is as follows:</p>
<pre class="code">http://10.94.238.84<strong>/admin/get_params.cgi?key</strong>
http://10.94.238.84<strong>/admin/set_params.cgi?key=value</strong>
</pre>

<p>The syntax of get/set requests for channel specific parameters is as follows:</p>
<pre class="code">http://10.94.238.84<strong>/admin/channelN/get_params.cgi?key</strong>
http://10.94.238.84<strong>/admin/channelN/set_params.cgi?key=value</strong>
</pre>

<p>One can specify several parameters in one URL, e.g.:</p>
<pre class="code">http://10.94.238.84<strong>/admin/channel2/get_params.cgi?codec&amp;framesize</strong>
http://10.94.238.84<strong>/admin/channel2/set_params.cgi?framesize=1280x1024&amp;codec=h.264</strong>
</pre>

<p>To save a JPEG snapshot:</p>
<pre class="code">http://10.94.238.84<strong>/admin/channelN/archive/snapshot.cgi</strong>
</pre>

<p>The syntax of get/set requests for multichannel recorders is as follows:</p>
<pre class="code">http://10.94.238.84<strong>/admin/recorderN/get_params.cgi?key</strong>
http://10.94.238.84<strong>/admin/recorderN/set_params.cgi?key=value</strong>
</pre>

<p>One can specify several parameters in one URL, e.g.:</p>
<pre class="code">http://10.94.238.84<strong>/admin/recorder2/get_params.cgi?rec_sizelimit&amp;rec_timelimit</strong>
http://10.94.238.84<strong>/admin/recorder2/set_params.cgi?rec_sizelimit=100000&amp;rec_timelimit=30:00</strong>
</pre>

<p>The syntax of get/set requests for system variables is as follows:</p>
<pre class="code">http://10.94.238.84<strong>/admin/get_variables.cgi?key</strong>
http://10.94.238.84<strong>/admin/set_variables.cgi?key=value</strong>
</pre>
<p><i>Note: The values of all system variables are lost after reboot of the device</i></p>

<p>One can specify several parameters in one URL, e.g.:</p>
<pre class="code">http://10.94.238.84<strong>/admin/get_variables.cgi?var1&amp;var2</strong>
http://10.94.238.84<strong>/admin/set_variables.cgi?var1=value1&amp;var2=value2</strong>
</pre>

<h2>Table of supported keys:</h2>

Main HTTP Server Settings
--
http_usessl | Enable SSL server: «on» to enable, anything else to disable
http_port | Port for HTTP Server
http_sport | Port for HTTPS Server
IP-based access control settings
allowips | Allowed IP addresses for live streams
denyips | Denied IP addresses for live streams
Common systems settings
name | Device name
description | Device description
location | Device location
multicast_ip | Multicast IPs (space separated) controlled by MULTICAST_RATE_LIMIT
multicast_rate_limit | Multicast rate limit in Mbps per destination IP
Firmware update settings
frmcheck_enabled | Enable check for firmware update. «on» — enable, empty — disable
Broadcasting settings
bcast_disabled | Disable broadcasting
streamport | Port for HTTP streaming
rtsp_port | Port for RTSP streaming
Common encoder settings
framesize | Size of encoded picture «WxH»
autoframesize | Use current signal resolution as frame size
fpslimit | Frame rate (frames per second)
vbitrate | Video bitrate in kbit/s
vencpreset | Video encoding preset: «0» — Software, «5» — Hardware Accelerated
vprofile | h.264 profile: «66» — Baseline, «77» — Main, «100» — High
vkeyframeinterval | Interval between key frames in encoded stream in seconds
qvalue | Quality parameter for Motion JPEG codec 0...100
codec | Video codec: «h.264» or «mjpeg»
audio | «on» — enable audio channel, empty — disable audio channel
audiopreset | Audio preset in format CODEC;SAMPLERATE (codecs: «pcm_s16le» — PCM, «libmp3lame» — MP3, «libfaac» — AAC; sample rates: «16000» (AAC only), «22050», «44100», «48000»)
audiobitrate | Audio bitrates in kbit/s («32», «64», «96», «112», «128», «160» or «192»). Not applicable for PCM audio codec.
audiochannels | Audio channels: «1» — mono, «2» — stereo
Channel layouts
active_layout | Active layout identifier
Stream access control
ac_override | «on» — override global stream access settings, empty — use global stream access settings
ac_viewerpwd | Viewer password
ac_allowips | Allowed IP addresses for live streams
ac_denyips | Denied IP addresses for live streams
Publish stream settings
publish_enabled | Publishing control: «on» — enabled, anything else — disabled
publish_type | Stream publish type: «0» — do not publish, «2» — RTSP announce, «3» — multicast RTP/UDP, «4» — multicast MPEG-TS over UDP, «5» — multicast MPEG-TS over RTP/UDP, «6» — RTMP push
RTSP Announce settings ( PUBLISH_TYPE = "2" )
rtsp_url | RTSP Server Announce URL
rtsp_transport | RTSP Transport
rtsp_username | RTSP Server Username
rtsp_password | RTSP Server Password
RTMP publish settings ( PUBLISH_TYPE = "6" )
rtmp_url | RTMP Server Announce URL
rtmp_stream | RTMP Stream
rtmp_username | RTMP Server Username
rtmp_password | RTMP Server Password
RTP/UDP publish settings ( PUBLISH_TYPE = "3" )
unicast_address | Unicast/multicast address
unicast_aport | UDP port number for audio stream
unicast_vport | UDP port number for video stream
MPEG-TS publish settings ( PUBLISH_TYPE = "4" and PUBLISH_TYPE = "5" )
unicast_address | Unicast/multicast address
unicast_mport | UDP port number for mpeg-ts stream
sap | «on» — enable SAP announcement, empty — disable
sap_ip | SAP announcement IP
sap_group | SAP group name
sap_channel_no | SAP channel name
Content metadata
title | A shorthand reference for media content
author | Contains preferably the name of the person who created the media content
copyright | Contains any necessary copyright notice for claiming the intellectual property for this media content
comment | Comments about media content
Recorder settings
rec_enabled | «on» if recorder started, empty otherwise
rec_sizelimit | File size limit in kB
rec_timelimit | File time limit in seconds
rec_format | Recording format: «avi», «mov», «mp4», «mp4f» or «ts»
rec_prefix | Custom filename prefix
Touch Screen settings
touchscreen_enabled | «on» — enable touch screen, empty — disable
touchscreen_preview | «on» — show preview
touchscreen_info | «on» — show system information
touchscreen_settings | «on» — allow change settings
touchscreen_recordctl | «on» — allow start/stop recording
touchscreen_timeout | inactivity timeout (seconds). «0» — no timeout
touchscreen_backlight | backlight level (0..255)
<hr>
</div>
`

**Comment by MarcHagen** [comment]
This module uses the newer API that the new GUI is also using.
Good to have this as a reference for the future, but this old api within the `/admin` is very limited in its functionality.
