### ISSUE TITLE
Start/Stop Recorder

### ISSUE THREAD

**Issue by Pippin1926** [bitfocus/companion-module-epiphan-pearl#8]
Hi there,

Could you add the trigger of recording of Recorders?
At the moment its only possible to trigger recording on Channels.

The Command is only little different, instead of /channelX/ its /channelmX/

Thanks!

**Comment by MarcHagen** [comment]
Its already possible to start and stop a dedicated recorder the latest version of Companion.
Which version are you using?

**Comment by Pippin1926** [comment]
Used the 2.1.3 today and it worked, maybe user error
