### ISSUE TITLE
Audio Input Analog A

### ISSUE THREAD

**Issue by shoude0203** [bitfocus/companion-module-epiphan-pearl#9]
XLR Input Analog A doesn‘t work correct. Everytime I don‘t give an audio signal to this port audio is gone, when putting it on again. Only a restart solves this problem. This is a big issue while Streaming.

**Comment by Pippin1926** [comment]
Epiphan is aware of this bug, they are trying to figure it out. The Input is crashing and isn't able to recover. It's stuck in a Bootloop after the crash.

They figured it's only on Input Analog A, should be fine using Analog B.

**Comment by MarcHagen** [comment]
Hi and welcome on Github.
I'm struggling to understand what a audio port has to do with a [Companion ](https://bitfocus.io/companion/) module ??
